language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - cd public/slunch-web
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod --aot

after_success:
  - cd ../.. 
  - firebase deploy --token $FIREBASE_TOKEN
