language: node_js
node_js:
  - "8"

branches:
  only:
    - master
    - dev

before_script:
  - cd functions
  - npm install
  - cd ../public/slunch-web
  - npm install
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - |
    if [ $TRAVIS_BRANCH == "master" ]; then
      ng build --prod --aot
    fi
    if [ $TRAVIS_BRANCH == "dev" ]; then
      ng build --aot
    fi
after_success:
  - |
    cd ../..
    if [ $TRAVIS_BRANCH == "master" ]; then
      firebase use prod
      firebase deploy --token $FIREBASE_TOKEN
    fi
    if [ $TRAVIS_BRANCH == "dev" ]; then
      firebase use dev
      firebase deploy --token $FIREBASE_TOKEN_DEV
    fi