language: node_js
node_js:
  - "8"

branches:
  only:
    - master
    - dev

before_script:
  - cd functions
  - npm install
  - cd ../public/slunch-web
  - npm install
  - npm install -g firebase-tools
  - npm install -g @angular/cli

deploy:
  script:
    - ng build --prod --aot
  after_success:
    - cd ../..
    - firebase use prod
    - firebase deploy --token $FIREBASE_TOKEN
  on:
    branch: master

deploy:
  script:
    - ng build --aot
  after_success:
    - cd ../..
    - firebase use dev
    - firebase deploy --token $FIREBASE_TOKEN_DEV
  on:
    branch: dev
  
